janata/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView
app_name="janata"
urlpatterns = [
    path('', jsonlist, name='jsonView'),
    # path('', StockListView.as_view(), name='home'),
     path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    # path('stock/add/', addStock, name='add'),
    # path('stock/<int:pk>/edit/', updateStock, name='edit'),
    # path('stock/<int:pk>/delete/', StockDeleteView.as_view(), name='delete'),

]

stock/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('janata.urls'))
]

janata/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Stock(models.Model):
    trade_code=models.CharField(max_length=255)
    date = models.DateField(default=timezone.now)
    high=models.FloatField()
    low=models.FloatField()
    open=models.FloatField()
    close=models.FloatField()
    volume=models.IntegerField()
    class Meta:
        ordering=['trade_code']

janata/forms.py
from dataclasses import fields
from pyexpat import model

from matplotlib import widgets
from .models import Stock
from django import forms

class CalendarWidget(forms.DateInput):
    input_type='date'

class StockForm(forms.ModelForm):

    class Meta:
        model=Stock
        fields= '__all__'
        widgets={
        'date': CalendarWidget(attrs={'class': "form-control"}),
        'trade_code': forms.TextInput(attrs={'class': "form-control"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['high'].widget.attrs.update({'class': 'form-control'})
        self.fields['low'].widget.attrs['class'] = 'form-control'
        self.fields['open'].widget.attrs.update({'class': 'form-control'})
        self.fields['close'].widget.attrs['class'] = 'form-control'
        self.fields['volume'].widget.attrs['class'] = 'form-control'

     

janata/views.py
from django.shortcuts import render,redirect, get_object_or_404
from pathlib import Path
import json
from django.core.paginator import Paginator,EmptyPage
from django.urls import reverse_lazy
from django.views import generic
from .forms import StockForm
from .models import Stock
from .filters import StockFilter
from django.contrib import messages
from csv import DictReader

# Create your views here.
def jsonlist(request):
    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent
    file=open(f'{BASE_DIR}/stock_market_data.json')
    stock_list = json.loads(file.read())
    paginator = Paginator(stock_list, 20) # Show 20 items per page.
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.get_page(page_number)
    except EmptyPage:
        #return last page if page limit exceeded
        page_obj = paginator.get_page(paginator.num_pages) 
    return render(request,'json-view.html',{'page_obj': page_obj,'is_paginated':True})

class StockListView(generic.ListView):
    model=Stock
    template_name='list.html'
    paginate_by=25
    
    def get_context_data(self, **kwargs) :
        ctx=super().get_context_data(**kwargs)
        filter=StockFilter()
        ctx['filter']=filter
        if self.request.GET.get('code'):
            ctx['plot_list']=Stock.objects.filter(trade_code=self.request.GET.get('code')).order_by('date')
        else:
            ctx['plot_list']=Stock.objects.order_by('date')
        
        if self.request.GET and len(self.request.GET)>0:
            querystring = self.request.GET.copy()
            if self.request.GET.get('page'):
                del querystring['page']
            ctx['querystring'] = querystring.urlencode()
            querystring={k:querystring[k] for k in querystring.keys() if querystring[k]!="" 
            and querystring[k] is not None}
            if len(querystring)>0:messages.info(self.request,'Search result')

        ctx['code_list']=Stock.objects.values('trade_code').distinct()
        return ctx
    
    def get_queryset(self):
        filter=StockFilter(self.request.GET,queryset=super().get_queryset())
        return filter.qs

def addStock(request):
    if request.method == 'POST':
        form=StockForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Item successfully added')
            return redirect('janata:home')
    else: form=StockForm()
    return render(request, 'create.html', {'form':form})


def updateStock(request,pk):
    a=get_object_or_404(Stock,pk=pk)
    form=StockForm(instance=a)
    if request.method == 'POST':
        form=StockForm(request.POST,instance=a)
        if form.is_valid():
            form.save()
            messages.success(request,'Item successfully updated')
            return redirect('janata:home')
    return render(request, 'edit.html', {'form':form})


class StockDeleteView(generic.DeleteView):
    model =Stock
    success_url = reverse_lazy('janata:home')
    def post(self, request, *args, **kwargs):
        messages.success(request,'Item successfully deleted')
        return super().post(request, *args, **kwargs)

janata/templates/about.html
{% extends './base.html'%}
{% block title %}About{% endblock %}
{% block content %}

<div class="card mx-auto shadow-sm w-50 mt-4">
  <h3 class="fw-bold card-header text-center">
    About this site
  </h3>
  <div class="card-body">
    <p class="card-text text-center fs-5">
      This site is a stock record system using Django.
  </div>
</div>

{% endblock %}

janata/templates/create.html
{% extends './base.html'%}
{% block title %}Add Stock{% endblock %}
{% block content %}

<div class="card mx-auto shadow-sm w-50 mt-4">
    <h4 class="fw-bold card-header text-center">
        Add your stock
    </h4>
    <div class="card-body">
      <p class="card-text">
        {% include "./form.html" %}
    </div>
  </div>
{% endblock %}

janata/templates/edit.html
{% extends './base.html'%}
{% block title %}Edit stock{% endblock %}
{% block content %}

<div class="card mx-auto shadow-sm w-50 mt-4">
    <h4 class="fw-bold card-header text-center">
        Edit your stock
    </h4>
    <div class="card-body">
      <p class="card-text">
        {% include "./form.html" %}
    </div>
  </div>

{% endblock %}

janata/templates/form.html
<form method="post" class="mt-2">
    {% csrf_token %}

    {% if form.non_field_errors %}
        <div class="text-danger text-center">{{ form.non_field_errors }}</div>
    {% endif  %}

    <div class="row mb-3">
        <label for="{{ form.trade_code.id_for_label }}" class="col-md-3 col-form-label text-md-end">Trade Code:</label>
        <div class="col-md-6">
            {{ form.trade_code }}
        </div>
    </div>
    {% if form.trade_code.errors %}
        <div class="text-danger text-center">{{ form.trade_code.errors }}</div>
    {% endif  %}

    <div class="row mb-3">
        <label for="{{ form.date.id_for_label }}" class="col-md-3 col-form-label text-md-end">Date:</label>
        <div class="col-md-6">
            {{ form.date }}
        </div>
    </div>
    {% if form.date.errors %}
        <div class="text-danger text-center">{{ form.date.errors }}</div>
    {% endif  %}
   
    <div class="row mb-3">
        <label for="{{ form.high.id_for_label }}" class="col-md-3 col-form-label text-md-end">High:</label>
        <div class="col-md-6">
            {{ form.high }}
        </div>
    </div>
    {% if form.high.errors %}
        <div class="text-danger text-center">{{ form.high.errors }}</div>
    {% endif  %}

    <div class="row mb-3">
        <label for="{{ form.low.id_for_label }}" class="col-md-3 col-form-label text-md-end">Low:</label>
        <div class="col-md-6">
            {{ form.low }}
        </div>
    </div>
    {% if form.low %}
        <div class="text-danger text-center">{{ form.low.errors }}</div>
    {% endif  %}
    
    <div class="row mb-3">
        <label for="{{ form.open.id_for_label }}" class="col-md-3 col-form-label text-md-end">Opening Price:</label>
        <div class="col-md-6">
            {{ form.open }}
        </div>
    </div>
    {% if form.open.errors %}
        <div class="text-danger text-center">{{ form.open.errors }}</div>
    {% endif  %}

    <div class="row mb-3">
        <label for="{{ form.close.id_for_label }}" class="col-md-3 col-form-label text-md-end">Closing Price:</label>
        <div class="col-md-6">
            {{ form.close }}
        </div>
    </div>
    {% if form.close.errors %}
        <div class="text-danger text-center">{{ form.close.errors }}</div>
    {% endif  %}

    <div class="row mb-3">
        <label for="{{ form.volume.id_for_label }}" class="col-md-3 col-form-label text-md-end">Trading Volume:</label>
        <div class="col-md-6">
            {{ form.volume }}
        </div>
    </div>
    {% if form.volume.errors %}
        <div class="text-danger text-center">{{ form.volume.errors }}</div>
    {% endif  %}
    
    
    <div class="d-grid gap-2 col-6 mx-auto">
        <button class="btn btn-primary" type="submit">Submit</button>
    </div>
</form>

janata/templates/list.html
{% extends './base.html' %}
{% block title %} Home {% endblock %}
{% block content %}

{% for message in messages %}
{% if message.tags == "success" %}

<div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
  <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
      <strong>Notice</strong>
      <button type="button" class="btn-close ms-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body text-success">
      {{ message }}
    </div>
  </div>
</div>      
{% endif %}
  {% endfor %}

{% if stock_list %}
<div class="bg-light w-75 mx-auto mt-4 mb-5">
  <canvas id="myChart"  class="d-block mx-auto" style="width:100%;max-width:950px"></canvas>
  <form class="mt-3">
    <div class="text-center">
      <select name="code" id="code">
        <option value="" disabled selected>Choose Trade Code</option>
        {% for code in code_list %}
        <option value="{{code.trade_code}}">{{code.trade_code}}</option>
        {% endfor %}
      </select>
      <input type="submit" value="Filter" class="btn btn-dark" style="padding: 0.05rem 1rem 0 1rem;margin-left: 0.2rem;margin-bottom: 0.15rem;">
    </div>
  </form>
</div>
<div class="card mx-auto mt-5 w-75">
  <h4 class="fw-bold card-header text-center">
      Search your stock
  </h4>
  <div class="card-body">
        <form class="card-text text-center row justify-content-around ms-2">
          <div class='col-md-3'>
            <label for="{{filter.form.trade_code__icontains.id_for_label}}">Trade Code:</label><br>
            {{filter.form.trade_code__icontains}}
          </div>
          <div class='col-md-2'>
            <label for="{{filter.form.date__gte.id_for_label}}">Start Date:</label><br>
            {{filter.form.date__gte}}
          </div>
          <div class='col-md-2'>
            <label for="{{filter.form.date__lte.id_for_label}}">End Date:</label><br>
            {{filter.form.date__lte}}
          </div>
          <div class='col-md-1'>
            <button type="submit" class="btn btn-secondary"><i class="fa fa-search"></i></button>
          </div>
        </form>
  </div>
</div>
{% for message in messages %}
      {% if message.tags == "info" %}
      <h6 class="display-6 text-center text-white mt-4">{{message}}</h6>
    {% endif %}
  {% endfor %}
<table class="table table-bordered table-light mt-5 mx-auto w-75">
<thead class="table-info">
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Trade Code </th>
      <th scope="col">High</th>
      <th scope="col">Low</th>
      <th scope="col">Opening Price</th>
      <th scope="col">Closing Price</th>
      <th scope="col">Trade Volume</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for item in  stock_list %}
    <tr>
        <th scope="row">{{ item.date }}</th>
        <td> {{ item.trade_code }} </td>
        <td> {{ item.high }}</td>
        <td>{{ item.low }}</td>
        <td>{{ item.open }}</td>
        <td>{{ item.close }}</td>
        <td>{{ item.volume }}</td>
        <td>
            <a class="btn btn-dark" href="{% url 'janata:edit' item.id %}" role="button">Edit</a>
            <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal-{{item.id}}">Delete</button> 
          <!-- Modal -->
  <div class="modal fade" id="deleteModal-{{item.id}}" tabindex="-1" aria-labelledby="exampleModalLabel-{{item.id}}" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel-{{item.id}}">Confirm Deletion</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'janata:delete' item.id %}" method="post" class="modal-body">
          {% csrf_token %}
          <p>Are you sure you want to delete this item?</p> 
          
          <div class="float-end">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-danger">Confirm</button>
          </div>
        </form>
      </div>
    </div>
  </div>
          </td>
      </tr>
      {% endfor %}
      </tbody>
  </table>
  {% if is_paginated %}
              <nav aria-label="Page navigation" >   
                  <ul class="pagination justify-content-center">
                  {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a class="page-link " href="{% url 'janata:home' %}{% if querystring %}?{{ querystring }}{% endif %}" aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="sr-only">first page</span>
                    </a>
                  </li>
                  <li class="page-item">
                    <a class="page-link " href="?page={{ page_obj.previous_page_number }}{% if querystring %}&amp;{{ querystring }}{% endif %}" aria-label="Previous">
                      Previous
                    </a>
                  </li>
                  {% endif %}
                  {% for n in page_obj.paginator.page_range %}
                    {% if page_obj.number == n %}
                      <li class="page-item active" >
                        <span class="page-link bg-dark  border-dark">{{ n }}<span class="sr-only">(current)</span></span>
                      </li>
                    {% elif n > page_obj.number|add:'-1' and n < page_obj.number|add:'5' %}
                      <li class="page-item"><a class="page-link " href="?page={{ n }}{% if querystring %}&amp;{{ querystring }}{% endif %}">{{ n }}</a></li>
                    {% endif %}
                  {% endfor %}
                  
                  {% if page_obj.has_next %}
                    <li class="page-item">
                      <a class="page-link " href="?page={{ page_obj.next_page_number }}{% if querystring %}&amp;{{ querystring }}{% endif %}" aria-label="Next">
                        Next
                      </a>
                    </li>
                    <li class="page-item">
                      <a class="page-link " href="?page={{ page_obj.paginator.num_pages }}{% if querystring %}&amp;{{ querystring }}{% endif %}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">last page</span>
                      </a>
                    </li>
                    {% endif %}   
                  </ul> 
                  </nav>

      {% endif %}
<script>

window.onload=(event)=>{
  let toastLiveExample = document.getElementById('liveToast');
  if (toastLiveExample) {
    let toast = new bootstrap.Toast(toastLiveExample,{delay:10000});
    toast.show()
  }
}

  const data = {
  labels: [{% for item in  plot_list %} '{{item.date}}',{% endfor %}],
  datasets: [{
    label: 'Trade Volume over Time',
    data: [{% for item in  plot_list %} {{item.volume}}, {% endfor %}],
    borderColor: 'rgb(110, 0, 0)',
    backgroundColor: 'rgb(218, 0, 0)',
    order: 2,
    yAxisID:'volume'
  }, {
    type: 'line',
    label:'Closing Price over Time',
    backgroundColor: "rgba(0,0,255,1.0)",
    borderColor: "rgba(0,0,255,0.1)",
    data: [{% for item in  plot_list %} {{item.close}}, {% endfor %}],
    order: 1
  }
]}

  let myChart = new Chart("myChart",  {
    type: 'bar',
  data: data,
  options: {
    scales: {
      y: {
        beginAtZero: true,
        title:{
          display:true,
          text:'Closing Price'
        }
      },
      volume: {
        title:{
          display:true,
          text:'Trading Volume'
        },
        position:'right',
      },
      x:{
        title:{
          display:true,
          text:'Date'
        }
      }
    }
  }
});


</script>
{% else %}
<p class="text-center text-white display-6 mt-3">No stocks found</p>
{% endif %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}My Site{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.js"></script>        
<!--<link rel="stylesheet" href="">-->
        <style>
          body{
            background-color: rgb(150, 65, 200);
            margin: 0;
            padding:0;
            font-family: 'Times New Roman', Times, serif;
          }

          .banner{
            font-family: cursive;
            font-style: italic;
            margin-left: 0.5rem;
            margin-top: 0.25rem;
            color:white
          }
          
        </style>
    </head>
    <body >
<h1 class="banner">Stock Records</h1>

<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'janata:jsonView' %}"><i class="fa fa-home" style="font-size:36px;color:white"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-white route" href="{% url 'janata:about' %}">About</a>
        </li>
        {% comment %}        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'janata:add' %}">Add Stock</a>
        </li>
 {% endcomment %}{% comment %}   
       <li class="nav-item">
               <a class="nav-link text-white" href="{% url 'janata:home' %}">JSON-view</a>
        </li>  {% endcomment %} 
    </div>
  </div>
</nav>
        
        {% block content %}

        {% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

templates/json-view.html
{% extends './base.html' %}
{% block title %}JSON View{% endblock %}
{% block content %}
{% if page_obj %}
<h1 class="display-6 text-center text-white mt-4">This table has been created using JSON data</h1>
<table class="table table-bordered table-light mt-4 mx-auto w-75">
<thead class="table-info">
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Trade Code </th>
      <th scope="col">High</th>
      <th scope="col">Low</th>
      <th scope="col">Opening Price</th>
      <th scope="col">Closing Price</th>
      <th scope="col">Trade Volume</th>
    </tr>
  </thead>
  <tbody>
    {% for item in  page_obj %}
    <tr>
        <th scope="row">{{ item.date }}</th>
        <td> {{ item.trade_code }} </td>
        <td> {{ item.high }}</td>
        <td>{{ item.low }}</td>
        <td>{{ item.open }}</td>
        <td>{{ item.close }}</td>
        <td>{{ item.volume }}</td>
        
      {% endfor %}
      </tbody>
  </table>
  {% if is_paginated %}
          <nav aria-label="Page navigation" >   
            <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link " href="?page=1{% if querystring %}&amp;{{ querystring }}{% endif %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">first page</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link " href="?page={{ page_obj.previous_page_number }}{% if querystring %}&amp;{{ querystring }}{% endif %}" aria-label="Previous">
                Previous
              </a>
            </li>   
            {% endif %}
            {% for n in page_obj.paginator.page_range %}
              {% if page_obj.number == n %}
                <li class="page-item active" >
                  <span class="page-link bg-dark  border-dark">{{ n }}<span class="sr-only">(current)</span></span>
                </li>
              {% elif n > page_obj.number|add:'-1' and n < page_obj.number|add:'5' %}
                <li class="page-item"><a class="page-link " href="?page={{ n }}{% if querystring %}&amp;{{ querystring }}{% endif %}">{{ n }}</a></li>
              {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link " href="?page={{ page_obj.next_page_number }}{% if querystring %}&amp;{{ querystring }}{% endif %}" aria-label="Next">
                  Next
                </a>
              </li>
              <li class="page-item">
                <a class="page-link " href="?page={{ page_obj.paginator.num_pages }}{% if querystring %}&amp;{{ querystring }}{% endif %}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                  <span class="sr-only">last page</span>
                </a>
              </li>
              {% endif %}  
                  </ul> 
                  </nav>

      {% endif %}
{% else %}
<p class="text-center text-white display-6 mt-3">No stocks found</p>
{% endif %}
{% endblock %}